version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=crawlertestdb
    volumes:
      - crawlertestdb_pg_data:/bitnami/postgresql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'

volumes:
  crawlertestdb_pg_data:
  elasticsearch_pg_data:
